### ISSUE TITLE
upstream fix for multisite deploys

### ISSUE THREAD

**Issue by strarsis** [strarsis/trellis-multisite-deployment-tests#1]
@bridgecrew-perf6: I noticed that you forked this repository. Originally this repository had been used to demonstrate an issue during multisite deploys. This issue is fixed now in upstream Trellis. I merged the fixed Trellis into this upstream, so multisite deployment now work with this project, too.

Relevant PRs:
- https://github.com/roots/trellis/pull/1391
- https://github.com/roots/trellis/pull/1388

You should pull the latest changes from this fork so you don't encounter this issue during multisite deploys.

**Comment by sniper7kills** [comment]
@strarsis If you look at that account; it looks like an automated tool someone is using to fork any repository that mentions "deployment". I'm guessing someone is looking for credentials that were mistakenly added to git repos. (5K+ forked repos in 27 days)
